# Generated by Django 6.0.2 on 2026-02-19 22:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار رسمی')),
                ('is_verified', models.BooleanField(default=False, null=True, verbose_name='تایید شده')),
                ('tagged_clue', models.TextField(help_text='مثال: این {def}تعریف{/def} و این {fod}مصالح{/fod} است.', null=True, verbose_name='متن معما با تگ')),
                ('clue_text', models.TextField(editable=False)),
                ('answer', models.CharField(max_length=50, verbose_name='پاسخ')),
                ('desc_definition', models.TextField(blank=True, default='توضیح تعریف', null=True, verbose_name='توضیح تعریف')),
                ('desc_fodder', models.TextField(blank=True, default=' توضیح مصالح', null=True, verbose_name='توضیح مصالح (Fodder)')),
                ('desc_indicators', models.TextField(blank=True, default='توضیح نشانگرها', null=True, verbose_name='توضیح نشانگرها')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='طراح')),
            ],
        ),
    ]
