# Generated by Django 6.0.2 on 2026-02-17 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='تاریخ انتشار')),
                ('clue_text', models.TextField(verbose_name='متن معما')),
                ('answer', models.CharField(max_length=50, verbose_name='پاسخ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='طراح معما')),
            ],
            options={
                'verbose_name': 'معما',
                'verbose_name_plural': 'معماها',
                'ordering': ['-date'],
            },
        ),
    ]
