# Generated by Django 6.0.2 on 2026-02-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='solve_count',
            field=models.IntegerField(default=0, verbose_name='تعداد دفعات حل'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='total_hints_used',
            field=models.IntegerField(default=0, verbose_name='مجموع راهنمایی\u200cهای استفاده شده'),
        ),
    ]
