# Generated by Django 6.0.2 on 2026-02-17 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puzzle',
            options={},
        ),
        migrations.AddField(
            model_name='puzzle',
            name='desc_definition',
            field=models.TextField(blank=True, verbose_name='توضیح تعریف'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='desc_fodder',
            field=models.TextField(blank=True, verbose_name='توضیح مصالح (Fodder)'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='desc_indicators',
            field=models.TextField(blank=True, verbose_name='توضیح نشانگرها'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='tagged_clue',
            field=models.TextField(help_text='مثال: این {def}تعریف{/def} و این {fod}مصالح{/fod} است.', null=True, verbose_name='متن معما با تگ'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='طراح'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='clue_text',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='date',
            field=models.DateField(unique=True, verbose_name='تاریخ انتشار'),
        ),
    ]
